# Generated by Django 6.0.6 on 2026-06-16 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesubmission',
            name='grading_status',
            field=models.CharField(choices=[('complete', 'Complete'), ('pending_manual', 'Pending Manual Grading')], default='complete', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank'), ('true_false', 'True or False'), ('fill_gap', 'Fill the Gap'), ('written', 'Written')], max_length=20),
        ),
        migrations.CreateModel(
            name='ExerciseAnswerGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_score', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_grades', to='assessments.exercisesubmission')),
            ],
            options={
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
