# Generated by Django 6.0.6 on 2026-06-15 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marhalah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('unlock_threshold', models.PositiveSmallIntegerField(default=0, help_text='Minimum final score % on previous marhalah to unlock')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'marhalahs',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('arabic_title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('arabic_content', models.TextField(blank=True)),
                ('examples', models.TextField(blank=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('is_published', models.BooleanField(default=True)),
                ('marhalah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.marhalah')),
            ],
            options={
                'ordering': ['marhalah', 'order'],
                'unique_together': {('marhalah', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TopicCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_completions', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='courses.topic')),
            ],
            options={
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
