import type {
  AdminStats,
  DashboardData,
  Exam,
  Exercise,
  Marhalah,
  Question,
  StudentProfile,
  Topic,
  User,
} from "@/lib/types";

export const mockUser: StudentProfile = {
  id: 1,
  email: "ahmad@example.com",
  first_name: "Ahmad",
  last_name: "Hassan",
  phone: "+966 50 123 4567",
  role: "student",
  registration_number: "TJW-2026-001",
  is_suspended: false,
  date_joined: "2026-01-15",
  current_marhalah: 1,
  progress_percent: 70,
  topics_completed: 8,
  total_topics: 9,
  overall_average: 72,
  has_attempted_exercise: true,
};

export const mockMarhalahs: Marhalah[] = [
  {
    id: 1,
    number: 1,
    title: "Marḥalah 1",
    unlock_threshold: 0,
    status: "open",
    topics_count: 9,
    topics_completed: 8,
    final_score: 72,
  },
  {
    id: 2,
    number: 2,
    title: "Marḥalah 2",
    unlock_threshold: 50,
    status: "locked",
    topics_count: 10,
    topics_completed: 0,
  },
  {
    id: 3,
    number: 3,
    title: "Marḥalah 3",
    unlock_threshold: 60,
    status: "locked",
    topics_count: 12,
    topics_completed: 0,
  },
  {
    id: 4,
    number: 4,
    title: "Marḥalah 4",
    unlock_threshold: 60,
    status: "locked",
    topics_count: 15,
    topics_completed: 0,
  },
];

export const mockTopics: Topic[] = [
  {
    id: 1,
    marhalah: 1,
    order: 1,
    title: "Al-Isti'adhah",
    arabic_title: "الاستعاذة",
    content: "Seeking refuge with Allah from Satan before recitation.",
    is_completed: true,
    status: "completed",
  },
  {
    id: 2,
    marhalah: 1,
    order: 2,
    title: "Al-Basmalah",
    arabic_title: "البسملة",
    content: "Saying Bismillah before beginning recitation.",
    is_completed: true,
    status: "completed",
  },
  {
    id: 3,
    marhalah: 1,
    order: 3,
    title: "Introduction to Tajweed",
    arabic_title: "مقدمة في التجويد",
    content: "Overview of Tajweed rules and their importance.",
    is_completed: true,
    status: "completed",
  },
  {
    id: 4,
    marhalah: 1,
    order: 4,
    title: "Al-Lahnu Al-Jali wa Al-Khafi",
    arabic_title: "اللحن الجلي والخفي",
    content: "Clear and hidden errors in Quranic recitation.",
    is_completed: true,
    status: "completed",
  },
  {
    id: 5,
    marhalah: 1,
    order: 5,
    title: "Idh-har Al-Halqi",
    arabic_title: "الإظهار الحلقي",
    content:
      "When Noon Sakinah or Tanween is followed by one of the six throat letters, the sound is pronounced clearly without assimilation.",
    arabic_content:
      "الإظهار الحلقي هو إخراج النون الساكنة أو التنوين عند لقائها بأحد حروف الحلق الستة",
    examples: "مِنْ عِلْمٍ — مِنْ هَادٍ — أَنْعَمْتَ",
    audio_url: "/audio/idhhar-halqi.mp3",
    is_completed: false,
    status: "active",
  },
  {
    id: 6,
    marhalah: 1,
    order: 6,
    title: "Idgham + Iqlab",
    arabic_title: "الإدغام والإقلاب",
    content: "Rules of assimilation and conversion.",
    is_completed: false,
    status: "locked",
  },
  {
    id: 7,
    marhalah: 1,
    order: 7,
    title: "Ikhfa'",
    arabic_title: "الإخفاء",
    content: "Hiding the noon sound with ghunnah.",
    is_completed: false,
    status: "locked",
  },
  {
    id: 8,
    marhalah: 1,
    order: 8,
    title: "Mim Sakinah",
    arabic_title: "الميم الساكنة",
    content: "Rules of the silent meem.",
    is_completed: false,
    status: "locked",
  },
  {
    id: 9,
    marhalah: 1,
    order: 9,
    title: "Idgham Mithlayn + Ikhfa'",
    arabic_title: "إدغام المثلين والإخفاء",
    content: "Combined rules of similar letter assimilation.",
    is_completed: false,
    status: "locked",
  },
];

export const mockExercises: Exercise[] = [
  {
    id: 1,
    marhalah: 1,
    title: "Exercise 1",
    start_date: "2026-03-01",
    end_date: "2026-03-15",
    status: "open",
    question_count: 20,
    score: 16,
    max_score: 20,
    has_submitted: true,
  },
  {
    id: 2,
    marhalah: 1,
    title: "Exercise 2",
    start_date: "2026-03-20",
    end_date: "2026-04-05",
    status: "upcoming",
    question_count: 15,
    has_submitted: false,
  },
];

export const mockExams: Exam[] = [
  {
    id: 1,
    marhalah: 1,
    title: "Marḥalah 1 Final Exam",
    duration_minutes: 60,
    start_date: "2026-04-10",
    end_date: "2026-04-20",
    status: "upcoming",
    question_count: 30,
    has_submitted: false,
  },
];

export const mockQuestions: Question[] = [
  {
    id: 1,
    type: "mcq",
    text: "Which of the following is an example of Idh-har Al-Halqi?",
    options: [
      "مِنْ عِلْمٍ",
      "مِنْ رَبِّهِمْ",
      "مِنْ يَعْمَلُ",
      "مِنْ وَلِيٍّ",
    ],
    order: 1,
  },
  {
    id: 2,
    type: "mcq",
    text: "How many throat letters are involved in Idh-har Al-Halqi?",
    options: ["4", "5", "6", "7"],
    order: 2,
  },
  {
    id: 3,
    type: "mcq",
    text: "Which letter is NOT a throat letter?",
    options: ["ء", "ه", "ع", "ق"],
    order: 3,
  },
];

export const mockDashboard: DashboardData = {
  greeting: "السلام عليكم Ahmad",
  registration_number: "TJW-2026-001",
  current_marhalah: mockMarhalahs[0],
  progress_percent: 70,
  topics_completed: 8,
  total_topics: 9,
  next_topic: mockTopics[4],
  marhalahs: mockMarhalahs,
  exercises: mockExercises,
  exams: mockExams,
  halaqah: { id: 1, type: "halaqah", score: 15, max_score: 20, marhalah: 1 },
  tadreeb: { id: 2, type: "tadreeb", score: 18, max_score: 20, marhalah: 1 },
  recent_results: {
    exercises: [
      { title: "Exercise 1", score: 16, max_score: 20 },
    ],
    exam: undefined,
    overall_average: 72,
  },
};

export const mockAdminStats: AdminStats = {
  total_students: 128,
  total_marhalahs: 4,
  total_topics: 72,
  total_assessments: 16,
};

export const mockStudents: User[] = [
  mockUser,
  {
    id: 2,
    email: "fatima@example.com",
    first_name: "Fatima",
    last_name: "Ali",
    role: "student",
    registration_number: "TJW-2026-002",
    is_suspended: false,
    date_joined: "2026-01-20",
  },
  {
    id: 3,
    email: "omar@example.com",
    first_name: "Omar",
    last_name: "Khan",
    role: "student",
    registration_number: null,
    is_suspended: false,
    date_joined: "2026-02-01",
  },
];
